
server:
  address: 0.0.0.0
  port: 7674
  max-http-header-size: 102400

sync:
  service-url: http://139.196.196.217:7001
  enterprise-id: 91310116789548291C
  public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCrBN1oBBGCWImETT76MCiGvlobwuYY7xMuMYIG0fQsUfx4ZLCcHlBXhhxE12GuLyq2TjGcU67Xd5r90GAxhFGoxK+3fDm7qq5IKIdP6EX9R6XhEuuOzGklCzk8hb5Yie/jSmxO/Q3QQIIjNGctsiFWOb7J+XdMIH1URooBonmI5wIDAQAB
